export const menuItems = [
  { name: "Home", href: "#home" },
  { name: "About", href: "#about" },
  { name: "Services", href: "#services" },
  { name: "Portfolio", href: "#portfolio" },
  { name: "Testimonials", href: "#testimonials" },
  { name: "Blog", href: "/#blog" },
];

export const helpdata: { icon: string; title: string; text: string }[] = [
  {
    icon: "/images/help/donation.svg",
    title: "Give donation",
    text: "Your donation funds vital programs and supports communities in need. Every contribution counts!",
  },
  {
    icon: "/images/help/volunteer.svg",
    title: "Become volunteer",
    text: "Join us in making a difference! Volunteer and work directly with our community projects. Every contribution counts!",
  },
  {
    icon: "/images/help/food-supply.svg",
    title: "Provide food supply",
    text: "Donate food supplies to help us combat hunger and support families in need. Every contribution counts!",
  },
];

export const CauseData: {
  image: string;
  title: string;
  slug: string;
  text: string;
  raised: string;
  goal: string;
}[] = [
    {
      image: "/images/causes/cause-1.jpg",
      title: "Give medical related help for african children",
      slug: "cause-1",
      text: "You can relay on our amazing features list and also our customer services will be great experience.",
      raised: "$65,360",
      goal: "$124,500",
    },
    {
      image: "/images/causes/cause-2.jpg",
      title: "Give small bunch of colors to little kids, joy of colors",
      slug: "cause-2",
      text: "You can relay on our amazing features list and also our customer services will be great experience.",
      raised: "$65,360",
      goal: "$124,500",
    },
    {
      image: "/images/causes/cause-3.jpg",
      title: "Send poor children to school to become superhero",
      slug: "cause-3",
      text: "You can relay on our amazing features list and also our customer services will be great experience.",
      raised: "$65,360",
      goal: "$124,500",
    },
    {
      image: "/images/causes/cause-4.jpg",
      title: "Uniting Hearts and Minds through Healthcare Outreach",
      slug: "cause-4",
      text: "You can relay on our amazing features list and also our customer services will be great experience.",
      raised: "$65,360",
      goal: "$124,500",
    },
    {
      image: "/images/causes/cause-5.jpg",
      title: "Auctioning Masterpieces to Support Arts Education in Schools",
      slug: "cause-5",
      text: "You can relay on our amazing features list and also our customer services will be great experience.",
      raised: "$65,360",
      goal: "$124,500",
    },
    {
      image: "/images/causes/cause-6.jpg",
      title: "Medical Mission Providing Care in Underserved Communities",
      slug: "cause-6",
      text: "You can relay on our amazing features list and also our customer services will be great experience.",
      raised: "$65,360",
      goal: "$124,500",
    },
    {
      image: "/images/causes/cause-7.jpg",
      title: "Empowering Women and Girls Through Education Initiatives",
      slug: "cause-7",
      text: "You can relay on our amazing features list and also our customer services will be great experience.",
      raised: "$65,360",
      goal: "$124,500",
    },
    {
      image: "/images/causes/cause-8.jpg",
      title: "Harnessing Renewable Energy for Environmental Conservation",
      slug: "cause-8",
      text: "You can relay on our amazing features list and also our customer services will be great experience.",
      raised: "$65,360",
      goal: "$124,500",
    },
    {
      image: "/images/causes/cause-9.jpg",
      title: "A Fundraising Gala for Education Equality and Access",
      slug: "cause-9",
      text: "You can relay on our amazing features list and also our customer services will be great experience.",
      raised: "$65,360",
      goal: "$124,500",
    },
  ];

export const Eventdata: {
  image: string;
  gallery: string[];
  title: string;
  isFeatured?: boolean;
  text: string;
  date: string;
  location: string;
  type: string;
  entrants: string;
  duration: string;
  category: string;
  detail: string;
  slug: string;
  video?: string;
}[] = [
    {
      image: "/images/event/kibalo1.jpg",
     gallery: [
        "/images/event/kibalo1.jpg",
        "/images/event/kibalo2.jpg",
        "/images/event/kibalo3.jpg",
        "/images/event/kibalo4.jpg",
        "/images/event/kibalo5.jpg",
        "/images/event/kibalo6.jpg",
        "/images/event/kibalo7.jpg",
        "/images/event/kibalo8.jpg",
        "/images/event/kibalo9.jpg",
        "/images/event/kibalo10.jpg",
        "/images/event/kibalo11.jpg",
        "/images/event/kibalo12.jpg",
        "/images/event/kibalo13.jpg",
        "/images/event/kibalo14.jpg",
        "/images/event/kibalo15.jpg",
        "/images/event/kibalo16.jpg",
        "/images/event/kibalo17.jpg",
        "/images/event/kibalo18.jpg",
        "/images/event/kibalo19.jpg",
        "/images/event/kibalo20.jpg",
        "/images/event/kibalo21.jpg",
        "/images/event/kibalo22.jpg",
        "/images/event/kibalo23.jpg",
        "/images/event/kibalo24.jpg",

      ],
      title: "You should have eagle's eye on new trends and techonogies",
      isFeatured: true,
      slug: "event-1",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
      video: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      image: "/images/event/kibalo24.jpg",
     gallery: [
        "/images/event/kibalo1.jpg",
        "/images/event/kibalo2.jpg",
        "/images/event/kibalo3.jpg",
        "/images/event/kibalo4.jpg",
        "/images/event/kibalo5.jpg",
        "/images/event/kibalo6.jpg",
        "/images/event/kibalo7.jpg",
        "/images/event/kibalo8.jpg",
        "/images/event/kibalo9.jpg",
        "/images/event/kibalo10.jpg",
        "/images/event/kibalo11.jpg",
        "/images/event/kibalo12.jpg",
        "/images/event/kibalo13.jpg",
        "/images/event/kibalo14.jpg",
        "/images/event/kibalo15.jpg",
        "/images/event/kibalo16.jpg",
        "/images/event/kibalo17.jpg",
        "/images/event/kibalo18.jpg",
        "/images/event/kibalo19.jpg",
        "/images/event/kibalo20.jpg",
        "/images/event/kibalo21.jpg",
        "/images/event/kibalo22.jpg",
        "/images/event/kibalo23.jpg",
        "/images/event/kibalo24.jpg",

      ],
      title: "New Seminar on Newest Food Recipe from World's Best",
      isFeatured: true,
      slug: "event-2",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
      video: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      image: "/images/event/kibalo7.jpg",
      gallery: [
        "/images/event/kibalo1.jpg",
        "/images/event/kibalo2.jpg",
        "/images/event/kibalo3.jpg",
        "/images/event/kibalo4.jpg",
        "/images/event/kibalo5.jpg",
        "/images/event/kibalo6.jpg",
        "/images/event/kibalo7.jpg",
        "/images/event/kibalo8.jpg",
        "/images/event/kibalo9.jpg",
        "/images/event/kibalo10.jpg",
        "/images/event/kibalo11.jpg",
        "/images/event/kibalo12.jpg",
        "/images/event/kibalo13.jpg",
        "/images/event/kibalo14.jpg",
        "/images/event/kibalo15.jpg",
        "/images/event/kibalo16.jpg",
        "/images/event/kibalo17.jpg",
        "/images/event/kibalo18.jpg",
        "/images/event/kibalo19.jpg",
        "/images/event/kibalo20.jpg",
        "/images/event/kibalo21.jpg",
        "/images/event/kibalo22.jpg",
        "/images/event/kibalo23.jpg",
        "/images/event/kibalo24.jpg",

      ],
      title: "You should have eagle’s eye on new trends and techonogies",
      isFeatured: true,
      slug: "event-1",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
    },
    {
      image: "/images/event/kibalo19.jpg",
      gallery: [
        "/images/event/kibalo19.jpg",
        "/images/event/kibalo19.jpg",
        "/images/event/kibalo19.jpg",
      ],
      title: "You should have eagle’s eye on new trends and techonogies",
      isFeatured: true,
      slug: "event-1",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
    },
    {
      image: "/images/event/kibalo7.jpg",
    gallery: [
        "/images/event/kibalo1.jpg",
        "/images/event/kibalo2.jpg",
        "/images/event/kibalo3.jpg",
        "/images/event/kibalo4.jpg",
        "/images/event/kibalo5.jpg",
        "/images/event/kibalo6.jpg",
        "/images/event/kibalo7.jpg",
        "/images/event/kibalo8.jpg",
        "/images/event/kibalo9.jpg",
        "/images/event/kibalo10.jpg",
        "/images/event/kibalo11.jpg",
        "/images/event/kibalo12.jpg",
        "/images/event/kibalo13.jpg",
        "/images/event/kibalo14.jpg",
        "/images/event/kibalo15.jpg",
        "/images/event/kibalo16.jpg",
        "/images/event/kibalo17.jpg",
        "/images/event/kibalo18.jpg",
        "/images/event/kibalo19.jpg",
        "/images/event/kibalo20.jpg",
        "/images/event/kibalo21.jpg",
        "/images/event/kibalo22.jpg",
        "/images/event/kibalo23.jpg",
        "/images/event/kibalo24.jpg",

      ],
      title: "You should have eagle’s eye on new trends and techonogies",
      isFeatured: true,
      slug: "event-1",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
    },
    {
      image: "/images/event/kibalo19.jpg",
     gallery: [
        "/images/event/kibalo1.jpg",
        "/images/event/kibalo2.jpg",
        "/images/event/kibalo3.jpg",
        "/images/event/kibalo4.jpg",
        "/images/event/kibalo5.jpg",
        "/images/event/kibalo6.jpg",
        "/images/event/kibalo7.jpg",
        "/images/event/kibalo8.jpg",
        "/images/event/kibalo9.jpg",
        "/images/event/kibalo10.jpg",
        "/images/event/kibalo11.jpg",
        "/images/event/kibalo12.jpg",
        "/images/event/kibalo13.jpg",
        "/images/event/kibalo14.jpg",
        "/images/event/kibalo15.jpg",
        "/images/event/kibalo16.jpg",
        "/images/event/kibalo17.jpg",
        "/images/event/kibalo18.jpg",
        "/images/event/kibalo19.jpg",
        "/images/event/kibalo20.jpg",
        "/images/event/kibalo21.jpg",
        "/images/event/kibalo22.jpg",
        "/images/event/kibalo23.jpg",
        "/images/event/kibalo24.jpg",

      ],
      title: "You should have eagle’s eye on new trends and techonogies",
      isFeatured: true,
      slug: "event-1",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
    },
    {
      image: "/images/event/kibalo19.jpg",
    gallery: [
        "/images/event/kibalo1.jpg",
        "/images/event/kibalo2.jpg",
        "/images/event/kibalo3.jpg",
        "/images/event/kibalo4.jpg",
        "/images/event/kibalo5.jpg",
        "/images/event/kibalo6.jpg",
        "/images/event/kibalo7.jpg",
        "/images/event/kibalo8.jpg",
        "/images/event/kibalo9.jpg",
        "/images/event/kibalo10.jpg",
        "/images/event/kibalo11.jpg",
        "/images/event/kibalo12.jpg",
        "/images/event/kibalo13.jpg",
        "/images/event/kibalo14.jpg",
        "/images/event/kibalo15.jpg",
        "/images/event/kibalo16.jpg",
        "/images/event/kibalo17.jpg",
        "/images/event/kibalo18.jpg",
        "/images/event/kibalo19.jpg",
        "/images/event/kibalo20.jpg",
        "/images/event/kibalo21.jpg",
        "/images/event/kibalo22.jpg",
        "/images/event/kibalo23.jpg",
        "/images/event/kibalo24.jpg",

      ],
      title: "You should have eagle’s eye on new trends and techonogies",
      isFeatured: true,
      slug: "event-1",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
    },
    {
      image: "/images/event/kibalo2.jpg",
    gallery: [
        "/images/event/kibalo1.jpg",
        "/images/event/kibalo2.jpg",
        "/images/event/kibalo3.jpg",
        "/images/event/kibalo4.jpg",
        "/images/event/kibalo5.jpg",
        "/images/event/kibalo6.jpg",
        "/images/event/kibalo7.jpg",
        "/images/event/kibalo8.jpg",
        "/images/event/kibalo9.jpg",
        "/images/event/kibalo10.jpg",
        "/images/event/kibalo11.jpg",
        "/images/event/kibalo12.jpg",
        "/images/event/kibalo13.jpg",
        "/images/event/kibalo14.jpg",
        "/images/event/kibalo15.jpg",
        "/images/event/kibalo16.jpg",
        "/images/event/kibalo17.jpg",
        "/images/event/kibalo18.jpg",
        "/images/event/kibalo19.jpg",
        "/images/event/kibalo20.jpg",
        "/images/event/kibalo21.jpg",
        "/images/event/kibalo22.jpg",
        "/images/event/kibalo23.jpg",
        "/images/event/kibalo24.jpg",

      ],
      title: "You should have eagle’s eye on new trends and techonogies",
      isFeatured: true,
      slug: "event-1",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
    },
    {
      image: "/images/event/kibalo2.jpg",
      gallery: [
        "/images/event/kibalo1.jpg",
        "/images/event/kibalo2.jpg",
        "/images/event/kibalo3.jpg",
        "/images/event/kibalo4.jpg",
        "/images/event/kibalo5.jpg",
        "/images/event/kibalo6.jpg",
      ],
      title: "You should have eagle’s eye on new trends and techonogies",
      isFeatured: true,
      slug: "event-1",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
    },
    {
      image: "/images/event/kibalo3.jpg",
      gallery: [
        "/images/event/kibalo3.jpg",
        "/images/event/kibalo4.jpg",
        "/images/event/kibalo5.jpg",
        "/images/event/kibalo6.jpg",
        "/images/event/kibalo7.jpg",
        "/images/event/kibalo8.jpg",
      ],
      title: "Learn from small things to create something bigger.",
      isFeatured: true,
      slug: "event-3",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
      video: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      image: "/images/event/kibalo4.jpg",
      gallery: [
        "/images/event/kibalo4.jpg",
        "/images/event/kibalo5.jpg",
        "/images/event/kibalo6.jpg",
        "/images/event/kibalo7.jpg",
        "/images/event/kibalo8.jpg",
        "/images/event/kibalo9.jpg",
        "/images/event/kibalo10.jpg",
      ],
      title: "Literary Escapade Book Reading and Discussion.",
      isFeatured: true,
      slug: "event-4",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
      video: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      image: "/images/event/kibalo5.jpg",
      gallery: [
        "/images/event/kibalo5.jpg",
        "/images/event/kibalo8.jpg",
        "/images/event/kibalo9.jpg",
        "/images/event/kibalo10.jpg",
        "/images/event/kibalo11.jpg",
        "/images/event/kibalo12.jpg",
      ],

      title: "A Journey Through Time Historical Reenactment Fair.",
      isFeatured: true,
      slug: "event-5",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
      video: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      image: "/images/event/kibalo6.jpg",
      gallery: [
        "/images/event/kibalo6.jpg",
        "/images/event/kibalo7.jpg",
        "/images/event/kibalo8.jpg",
        "/images/event/kibalo9.jpg",
        "/images/event/kibalo10.jpg",
        "/images/event/kibalo11.jpg",
      ],
      title: "Leadership Summit Empowering Tomorrow's Leaders.",
      isFeatured: true,
      slug: "event-6",
      text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
      date: "May 10, 2024",
      location: "San Marcos",
      type: "Open",
      entrants: "Unlimited",
      duration: "1655 Days",
      category: "Calendar, Dontaions",
      detail:
        "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
      video: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
  ];

export const footerLinks: { link: string }[] = [
  {
    link: "Medical crowdfunding",
  },
  {
    link: "Cancer Crowdfunding",
  },
  {
    link: "Transplant Crowdfunding",
  },
  {
    link: "Education Crowdfunding",
  },
  {
    link: "Child Welfare",
  },
  {
    link: "Medical Finance",
  },
  {
    link: "FAQs & Help Center",
  },
  {
    link: "Fundraiser Video",
  },
  {
    link: "Trust & Safety",
  },
  {
    link: "Plans & Pricing*",
  },
];

export const Reviews: {
  clientImg: string;
  clientName: string;
  review: string;
  post: string;
}[] = [
    {
      clientImg: "/images/testimonial/client-1.jpg",
      clientName: "Michelle Anderson",
      review:
        "You can relay on our amazing features list and also our customer services will be great experience. You can relay on our amazing features.",
      post: "CEO, Theme Designer",
    },
    {
      clientImg: "/images/testimonial/client-2.jpg",
      clientName: "Michelle Anderson",
      review:
        "You can relay on our amazing features list and also our customer services will be great experience. You can relay on our amazing features.",
      post: "Managing Director, Theme Designer",
    },
  ];
